### ISSUE TITLE
Editing Task content focus keyboard problem

### ISSUE THREAD

**Issue by Bodaymat** [HellBus1/VentNote#15]
When editing a task, only when clicking on the title textfield will the keyboard show up. Otherwise, even if you keep clicking in the content textfield, the keyboard stays hidden.

**Comment by HellBus1** [comment]
Thanks @Bodaymat , the issues is already fixed and it will shows keyboard either you click on title, body, or one of them twice

**Comment by HellBus1** [comment]
Thanks @Bodaymat , the issues is already fixed and it will shows keyboard either you click on title, body, or one of them twice
