### ISSUE TITLE
Temporary After Edit revert bug

### ISSUE THREAD

**Issue by Bodaymat** [HellBus1/VentNote#16]
After you edit a task and cancel your changes, unless you close and reopen the task, your changes will still show until refreshed.

**Comment by HellBus1** [comment]
Could you elaborate more? the current flow of editing task is following :
1. Press edit, it will turn field to be editable
2. If you press close or back it will show dialog wether you confirm to cancel edited data or dismiss the dialog
3. If you press check fab, it will proceed to edit

**Comment by HellBus1** [comment]
its fixed already, check it out. Thank you for the report
